# docker-compose.yml

services:
  postgres:
    container_name: tax-declaration-postgres
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  tax-declaration-api:
    build:
      context: ./server
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

  tax-declaration-web:
    build:
      context: ./web
    env_file:
      - .env
    ports:
      - 8081:80
    depends_on:
      - tax-declaration-api

volumes:
  postgres-data:
    driver: local
