version: '3.8'

services:
  postgres:
    container_name: tax-declaration-postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tax-declaration-db
    ports:
      - 5432:5432
